version: '3'   # on CircleCI the version and services cause build to puke.
services:

  blacklight:
    build:
      context: ./blacklight
      dockerfile: Dockerfile
    volumes:
      - ./blacklight/app:/app/app
    ports:
      - "4000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - SOLR_URL=http://solr1:8983/solr/ecommerce
#    networks:
#      - solr
    depends_on:
      - solr1

  mysql:
    container_name: mysql
    image: mysql:5.7.29
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  smui:
    container_name: smui
    #image: querqy/smui:3.6.1
    build:
      context: ./smui
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      - SMUI_DB_URL=jdbc:mysql://mysql:3306/smui?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - SMUI_DB_USER=root
      - SMUI_DB_PASSWORD=password
      - SMUI_DEPLOY_PRELIVE_SOLR_HOST=solr1:8983
      - SMUI_TOGGLE_DEPL_CUSTOM_SCRIPT=true
      - SMUI_TOGGLE_DEPL_CUSTOM_SCRIPT_PATH=/smui/conf/smui2solrcloud.sh
      - SMUI_DEPLOY_PRELIVE_FN_RULES_TXT=/configs/ecommerce/rules.txt
    #volumes:
      #- ./volumes/preliveCore/conf:/usr/bin/solr/preliveCore/conf
    depends_on:
      - mysql

  solr1:
    container_name: solr1
    #image: solr:8
    build: ./solr
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./volumes/fake_shared_fs:/tmp/fake_shared_fs
 #   networks:
 #     - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr2:
    container_name: solr2
    #image: solr:8
    build: ./solr
    ports:
     - "8984:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./volumes/fake_shared_fs:/tmp/fake_shared_fs
 #   networks:
 #     - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr3:
    container_name: solr3
    #image: solr:8
    build: ./solr
    ports:
     - "8985:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./volumes/fake_shared_fs:/tmp/fake_shared_fs
 #   networks:
 #     - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  zoo1:
    image: zookeeper:3.5
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
 #   networks:
 #     - solr

  zoo2:
    image: zookeeper:3.5
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
 #   networks:
 #     - solr

  zoo3:
    image: zookeeper:3.5
    container_name: zoo3
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
 #   networks:
 #     - solr

  redis:
    container_name: quepid_redis
    image: redis:6.0.5
    ports:
      - 6379:6379

  quepid:
    container_name: quepid
    image: o19s/quepid:6.2.2
    ports:
      - 3000:3000
    command: "foreman s -f Procfile"
    environment:
      - PORT=3000
      - RACK_ENV=production
      - RAILS_ENV=production
      - DATABASE_URL=mysql2://root:password@mysql:3306/quepid
      - REDIS_URL=redis://redis:6379/1
      - FORCE_SSL=false
      - MAX_THREADS=2
      - WEB_CONCURRENCY=2
      - SECRET_KEY_BASE=some_value_needed_here
      - TC_URL=
      - PRIVACY_URL=
      - COOKIES_URL=
      - EMAIL_MARKETING_MODE=false
      - QUEPID_DEFAULT_SCORER=AP@5
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis

  rre:
    build:
      context: ./rre
      dockerfile: Dockerfile
    volumes:
      - ./rre:/rre
    ports:
      - "7979:8080"
    command: "java -jar rre-server-1.1.jar"
    environment:
      - SOLR_URL=http://solr1:8983/solr/ecommerce
    depends_on:
      - solr1

volumes:
    mysql_data: {}

#networks:
#  solr:
