# Does the Docker setup work?
name: chorus-smoke-test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Keycloak address
        run: echo "127.0.0.1  keycloak" >> /etc/hosts
      - name: Build the stack
        run: ./quickstart.sh
      - name: Test
        run: docker run --network container:solr1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8983/solr/ecommerce/admin/ping
        #run: docker run --network container:quepid appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000
        #run: docker run --network container:rre appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080
        #run: docker run --network container:blacklight appropriate/curl --retry 10 --retry-connrefused http://localhost:3000/
